# Derived from https://github.com/actions/starter-workflows/blob/main/ci/python-app.yml
# and https://github.com/ukri-excalibur/excalibur-tests/blob/main/.github/workflows/ci.yml
name: UKRI NEMO CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Spack
      run: |
        git clone --depth=2 --branch=releases/v1.0.0-alpha4 https://github.com/spack/spack.git ~/spack
        source ~/spack/share/spack/setup-env.sh
    # Make sure `spack` command works
    - name: Spack version number
      shell: bash
      run: spack --version

