name: UKRI NEMO CI

on:
  # Uncomment the below 'push' to trigger on push
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - main
  merge_group:
    branches:
    - main
  # schedule:
  #   # '*' is a special character in YAML, so string must be quoted
  #   - cron: "0 2 * * THU"
  workflow_dispatch:

env:
  GITHUB_USER: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop    # Spack version (examples: develop, releases/v0.23)
          color: true     # Force color output (SPACK_COLOR=always)
          path: spack-src # Where to clone Spack      # - name: Get Spack

      - name: Get Spack config (CPU)
        run: |
          wget -O spack.yml https://raw.githubusercontent.com/ukri-bench/spack-configs/refs/heads/main/configs/gh-actions/spack.yml

      - name: Add ukri-bench Spack repository and create environment
        shell: spack-bash {0}
        run: |
          spack repo add --name bench_pkgs https://github.com/ukri-bench/spack-packages.git bench_pkgs
          spack env create . spack.yml
          #spack -e . mirror add --unsigned --type binary --oci-username-variable GITHUB_USER --oci-password-variable GITHUB_TOKEN local-buildcache oci://ghcr.io/ukri-bench/spack-buildcache-nemo
          #spack -e . config get mirrors

      - name: Install NEMO
        shell: spack-bash {0}
        run: |
          #spack -e . install --use-buildcache=package:never,dependencies:auto --add nemo +mpi config=ORCA2_ICE_PISCES %gcc
          spack -e . install --add nemo +mpi config=ORCA2_ICE_PISCES %gcc


      - name: Push packages and update index
        shell: spack-bash {0}
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: spack -e . buildcache push --base-image ubuntu:24.04 --update-index local-buildcache
        if: ${{ !cancelled() }}

      - name: Get extra files for ORCA2_ICE_PISCES
        run: |
          curl -O https://gws-access.jasmin.ac.uk/public/nemo/sette_inputs/r4.2.0/ORCA2_ICE_v4.2.0.tar.gz
          tar -xvzf ORCA2_ICE_v4.2.0.tar.gz

      - name: Install gnuplot  # Required for timings output
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gnuplot

      - name: Prepare run script
        shell: spack-bash {0}
        run: |
          spack env activate .
          nemo-wrapper -i 2 -j 2 +stats +timings --extra-paths "$PWD/ORCA2_ICE_v4.2.0"

      - name: Run NEMO
        shell: spack-bash {0}
        run: |
          spack env activate .
          cd ./NEMO_RUNDIR
          mpirun -np 4 ./nemo

      - name: Get error logs for nemo
        run: cat ./NEMO_RUNDIR/ocean.output

      - name: Get timings for nemo
        run: cat ./NEMO_RUNDIR/timing.output
