# Derived from https://github.com/actions/starter-workflows/blob/main/ci/python-app.yml
# and https://github.com/ukri-excalibur/excalibur-tests/blob/main/.github/workflows/ci.yml
# and https://github.com/marketplace/actions/setup-spack
name: UKRI NEMO CI

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Set up Spack
      uses: spack/setup-spack@v2
      with:
        ref: v1.0.0-alpha.4 # Spack version (examples: develop, releases/v0.23)
        buildcache: true    # Configure oci://ghcr.io/spack/github-actions-buildcache
        color: true         # Force color output (SPACK_COLOR=always)
        path: spack         # Where to clone Spack
    # Make sure `spack` command works
    - name: Spack version number
      shell: bash
      run: spack --version
    - name: Spack install gcc11
      run: spack install gcc@11
    - name: Install f90nml
      run: spack install py-f90nml%gcc@11
    - name: Add NEMO package repository
      run: spack repo add .
    - name: Spack install NEMO
      run: spack install nemo%gcc@11 +mpi config=ORCA2_ICE_PISCES

